export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const COUNTRY_BY_NAME = "COUNTRY_BY_NAME";
export const POST_ACTIVITY = "POST_ACTIVITY";